version: '3.8'

services:

  web:
    image: fyk7/celery-fastapi-text-vect-api
    build:
      dockerfile: Dockerfile.api
      context: .
    ports:
      - 8008:8000
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/usr/src/app
      - ./bert-cache:/root/.cache/huggingface/transformers
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  worker:
    image: fyk7/celery-fastapi-text-vect-worker
    build:
      dockerfile: Dockerfile.worker
      context: .
    command: celery --app=src.worker.worker.celery worker --pool=solo --loglevel=info --logfile=src/worker/logs/celery.log
    volumes:
      - .:/usr/src/app
      - ./bert-cache:/root/.cache/huggingface/transformers
    environment:
      - REDIS_HOST=redis
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine

  # dashboard:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./src/worker
  #   command:  flower --app=worker.celery --port=5555 --broker=redis://redis:6379/0
  #   ports:
  #     - 5556:5555
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - web
  #     - redis
  #     - worker
