apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: fastapi
  template:
    metadata:
      labels:
        pod: fastapi
    spec:
      containers:
        - name: fastapi
          # image: fyk7/celery-fastapi-text-vect-api:latest
          image: gcr.io/text-vec/fyk7/celery-fastapi-text-vect-api
          ports:
            - containerPort: 8000
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              # <service_name>.<namespace>であることに注意
              value: redis-service.redis-textvec
