apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: textvec
bases:
- ../../base
namePrefix: stg-
namespace: textvec-stg
commonLabels:
  app: textvec-stg
images:
  - name: fastapi
    newName: gcr.io/text-vec/fyk7/celery-fastapi-text-vect-api
  - name: celery-worker
    newName: gcr.io/text-vec/fyk7/celery-fastapi-text-vect-worker 
# replicas:
# - name: fastapi
#   count: 2
patchesStrategicMerge:
- ../../overlays/stg/fastapi/deployment.yaml
